// app/lib/constants/carProperties.ts

export type searchValue =
  | "marques"
  | "typesCarrosserie"
  | "anneeMin"
  | "anneeMax"
  | "kilometrageMin"
  | "kilometrageMax"
  | "PrixMin"
  | "PrixMax"
  | "typeMoteur"
  | "typeCarburant"
  | "selectedColor"
  | "keyword"
  | "typeTransmission"
  | "villeDuBien";

export const MARQUES = [
  "Toyota",
  "Mitsubishi",
  "Suzuki",
  "Nissan",
  "Honda",
  "Peugeot",
  "Renault",
  "Citroën",
  "Volkswagen",
  "BMW",
  "Mercedes",
  "Audi",
  "Ford",
  "Chevrolet",
  "Hyundai",
  "Kia",
  "Opel",
  "Autre",
  // Ajoutez d'autres marques...
] as const;

export const TYPES_CARROSSERIE = [
  "Berline",
  "SUV",
  "Break",
  "Monospace",
  "Coupé",
  "Cabriolet",
  // Ajoutez d'autres types...
] as const;

export const FUEL_TYPES = [
  "Essence",
  "Diesel",
  "Hybride",
  "Electrique",
  "GPL",
  // Ajoutez d'autres carburants...
] as const;

export const TRANSMISSION_TYPES = [
  "Manuelle",
  "Automatique",
  "Semi_automatique",
  // Ajoutez d'autres transmissions...
] as const;

export const TYPE_TRAIN_CONDUCTEUR = [
  "Traction avant (FWD)",
  "Propulsion arrière (RWD)",
  "Transmission intégrale permanante (HWD)",
  "Tranmission integrale enclanchable (4WD)",
] as const;

export const MIN_YEAR = [
  1980, 1984, 1990, 1994, 1998, 2002, 2006, 2010, 2012, 2014, 2016, 2018, 2020,
  2022, 2024, 2025,
];

export const TYPES_MOTEUR = ["CYLINDRE4", "CYLINDRE6", "ELECTRIQUE"] as const;

export const CURRENCIES = ["FCFA", "USD", "EUR", "CAD"] as const;
export const MILEAGE_UNITS = ["km", "miles"] as const;

export const villesCameroun = [
  "Yaoundé",
  "Douala",
  "Bamenda",
  "Bafoussam",
  "Garoua",
  "Maroua",
  "Ngaoundéré",
  "Bertoua",
  "Ebolowa",
  "Kumba",
  "Limbe",
  "Buea",
  "Edéa",
  "Foumban",
  "Dschang",
  "Kribi",
  "Nkongsamba",
  "Mbalmayo",
  "Meiganga",
  "Bafia",
  "Eseka",
  "Kumbo",
  "Mbouda",
  "Tiko",
  "Bangangté",
  "Obala",
  "Mokolo",
  "Mora",
  "Sangmélima",
  "Batouri",
  "Banyo",
  "Abong-Mbang",
  "Fundong",
  "Manjo",
  "Tibati",
  "Wum",
  "Akono",
  "Ambam",
  "Bali",
  "Bamendjou",
  "Bana",
  "Bandjoun",
  "Bankim",
  "Bazou",
  "Belabo",
  "Bekondo",
  "Belo",
  "Bétaré-Oya",
  "Bogo",
  "Bonabéri",
  "Bot-Makak",
  "Bélabo",
  "Dibombari",
  "Dimako",
  "Djohong",
  "Doumé",
  "Eséka",
  "Figuil",
  "Fontem",
  "Foumbot",
  "Guider",
  "Kaélé",
  "Lagdo",
  "Mamfé",
  "Mandjou",
  "Mbang",
  "Mbanga",
  "Mbandjock",
  "Mengueme",
  "Mfou",
  "Mindif",
  "Minta",
  "Mvangué",
  "Ndikiniméki",
  "Ngambe",
  "Ngoro",
  "Ngoulemakong",
  "Njinikom",
  "Nkambe",
  "Nkoteng",
  "Okola",
  "Penja",
  "Pitoa",
  "Poli",
  "Rey-Bouba",
  "Sa'a",
  "Tcholliré",
  "Tibati",
  "Tombel",
  "Touboro",
  "Yagoua",
  "Yokadouma",
  "Zhoa",
];

export const COULEURS = [
  { nom: "Noir profond", hexa: "#0A0A0A" },
  { nom: "Noir métallisé", hexa: "#1C1C1C" },
  { nom: "Blanc nacré", hexa: "#F8F8FF" },
  { nom: "Blanc cassé", hexa: "#F5F5F5" },
  { nom: "Blanc glacier", hexa: "#E1E1E1" },
  { nom: "Gris anthracite", hexa: "#2B2B2B" },
  { nom: "Gris acier", hexa: "#71706C" },
  { nom: "Gris titane", hexa: "#878681" },
  { nom: "Gris nardo", hexa: "#8E8E8E" },
  { nom: "Gris shark", hexa: "#6D6D6D" },
  { nom: "Gris quartz", hexa: "#4C4C4C" },
  { nom: "Gris storm", hexa: "#585858" },
  { nom: "Gris moonrock", hexa: "#B8B8B8" },
  { nom: "Gris gunmetal", hexa: "#2C3539" },
  { nom: "Argent métallisé", hexa: "#C0C0C0" },
  { nom: "Argent chromé", hexa: "#D4D4D4" },
  { nom: "Bleu marine", hexa: "#000080" },
  { nom: "Bleu nuit", hexa: "#0F056B" },
  { nom: "Bleu roi", hexa: "#0038A8" },
  { nom: "Bleu électrique", hexa: "#0066CC" },
  { nom: "Bleu Laguna", hexa: "#1E90FF" },
  { nom: "Bleu horizon", hexa: "#87CEEB" },
  { nom: "Bleu petrol", hexa: "#005F6A" },
  { nom: "Bleu de France", hexa: "#318CE7" },
  { nom: "Bleu navy", hexa: "#000F5C" },
  { nom: "Bleu métallisé", hexa: "#1F75FE" },
  { nom: "Bleu glacier", hexa: "#78B4C6" },
  { nom: "Bleu turquoise", hexa: "#40E0D0" },
  { nom: "Bleu pastel", hexa: "#A7C7E7" },
  { nom: "Bleu marine métallisé", hexa: "#1A2B5F" },
  { nom: "Rouge Ferrari", hexa: "#FF2800" },
  { nom: "Rouge sang", hexa: "#CC0000" },
  { nom: "Rouge vif", hexa: "#FF0000" },
  { nom: "Rouge bordeaux", hexa: "#800020" },
  { nom: "Rouge cerise", hexa: "#990000" },
  { nom: "Rouge corail", hexa: "#FF4040" },
  { nom: "Rouge Mazda", hexa: "#A91C1C" },
  { nom: "Rouge passion", hexa: "#E41B17" },
  { nom: "Rouge métallisé", hexa: "#B22222" },
  { nom: "Rouge rubis", hexa: "#9B111E" },
  { nom: "Vert British Racing", hexa: "#004225" },
  { nom: "Vert forêt", hexa: "#228B22" },
  { nom: "Vert émeraude", hexa: "#50C878" },
  { nom: "Vert menthe", hexa: "#98FF98" },
  { nom: "Vert olive", hexa: "#808000" },
  { nom: "Vert kaki", hexa: "#6B8E23" },
  { nom: "Vert pomme", hexa: "#7CFC00" },
  { nom: "Vert jade", hexa: "#00A86B" },
  { nom: "Vert lime", hexa: "#32CD32" },
  { nom: "Vert armée", hexa: "#4B5320" },
  { nom: "Jaune citron", hexa: "#FFF44F" },
  { nom: "Jaune or", hexa: "#FFD700" },
  { nom: "Jaune taxi", hexa: "#F5C300" },
  { nom: "Jaune moutarde", hexa: "#FFDB58" },
  { nom: "Jaune pastel", hexa: "#FDFD96" },
  { nom: "Jaune fluo", hexa: "#FFFF00" },
  { nom: "Orange brûlé", hexa: "#CC5500" },
  { nom: "Orange vif", hexa: "#FFA500" },
  { nom: "Orange corail", hexa: "#FF7F50" },
  { nom: "Orange métallisé", hexa: "#E67E22" },
  { nom: "Orange mandarine", hexa: "#F28500" },
  { nom: "Marron chocolat", hexa: "#7B3F00" },
  { nom: "Marron café", hexa: "#6F4E37" },
  { nom: "Marron caramel", hexa: "#AF6E4D" },
  { nom: "Marron cuir", hexa: "#8B4513" },
  { nom: "Marron taupe", hexa: "#483C32" },
  { nom: "Beige sable", hexa: "#F5DEB3" },
  { nom: "Beige champagne", hexa: "#F7E7CE" },
  { nom: "Beige camel", hexa: "#C19A6B" },
  { nom: "Beige ivoire", hexa: "#FFFFF0" },
  { nom: "Beige moka", hexa: "#E1C78F" },
  { nom: "Rose poudré", hexa: "#FFC0CB" },
  { nom: "Rose bonbon", hexa: "#FF69B4" },
  { nom: "Rose saumon", hexa: "#FF9999" },
  { nom: "Rose métallisé", hexa: "#E0BFB8" },
  { nom: "Rose gold", hexa: "#B76E79" },
  { nom: "Violet améthyste", hexa: "#9966CC" },
  { nom: "Violet profond", hexa: "#800080" },
  { nom: "Violet métallisé", hexa: "#8A2BE2" },
  { nom: "Violet lavande", hexa: "#967BB6" },
  { nom: "Violet orchidée", hexa: "#DA70D6" },
  { nom: "Bronze", hexa: "#CD7F32" },
  { nom: "Bronze métallisé", hexa: "#B1560F" },
  { nom: "Cuivre", hexa: "#B87333" },
  { nom: "Or", hexa: "#D4AF37" },
  { nom: "Or rose", hexa: "#E0BFB8" },
  { nom: "Or métallisé", hexa: "#FFD700" },
  { nom: "Champagne", hexa: "#F7E7CE" },
  { nom: "Champagne rosé", hexa: "#F3D9B1" },
  { nom: "Turquoise", hexa: "#40E0D0" },
  { nom: "Turquoise métallisé", hexa: "#00CED1" },
  { nom: "Bordeaux", hexa: "#800020" },
  { nom: "Bordeaux métallisé", hexa: "#5C0120" },
  { nom: "Corail", hexa: "#FF7F50" },
  { nom: "Corail métallisé", hexa: "#E3735E" },
  { nom: "Graphite", hexa: "#251607" },
  { nom: "Graphite métallisé", hexa: "#383E42" },
  { nom: "Noir bleuté", hexa: "#0A1A2A" },
  { nom: "Noir rougeâtre", hexa: "#1A0000" },
  { nom: "Blanc perle", hexa: "#EAE6CA" },
  { nom: "Blanc diamant", hexa: "#F0F0F0" },
  { nom: "Gris perle", hexa: "#C5C5C5" },
  { nom: "Bleu perle", hexa: "#A7C7E7" },
  { nom: "Rouge perle", hexa: "#B22222" },
  { nom: "Vert perle", hexa: "#7CFC00" },
  { nom: "Effet miroir", hexa: "#D4D4D4" },
  { nom: "Chrome", hexa: "#E8E8E8" },
  { nom: "Noir mat", hexa: "#0D0D0D" },
  { nom: "Gris mat", hexa: "#3A3A3A" },
  { nom: "Militaire mat", hexa: "#555555" },
  { nom: "Bleu mat", hexa: "#1F75FE" },
  { nom: "Rouge mat", hexa: "#990000" },
  { nom: "Vert mat", hexa: "#4B5320" },
];

export const COULEURS2 = [
  { name: "Black", hex: "#000000" },
  { name: "Blue", hex: "#0000FF" },
  { name: "Brown", hex: "#964B00" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Green", hex: "#008000" },
  { name: "Gray", hex: "#808080" },
  { name: "Pink", hex: "#FFC0CB" },
  { name: "Purple", hex: "#800080" },
  { name: "Red", hex: "#FF0000" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Orange", hex: "#FFA500" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "Charcoal", hex: "#36454F" },
  { name: "Tan", hex: "#D2B48C" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Burgundy", hex: "#800020" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Metallic Black", hex: "#1A1A1A" },
  { name: "Metallic Graphite Black", hex: "#2B2B2B" },
  { name: "Metallic Black Steel", hex: "#262626" },
  { name: "Metallic Dark Silver", hex: "#71706C" },
  { name: "Metallic Silver", hex: "#A6A6A6" },
  { name: "Metallic Blue Silver", hex: "#7D9EC0" },
  { name: "Metallic Steel Gray", hex: "#6D6D6D" },
  { name: "Metallic Shadow Silver", hex: "#7A7A7A" },
  { name: "Metallic Stone Silver", hex: "#8E8E8E" },
  { name: "Metallic Midnight Silver", hex: "#4A4A4A" },
  { name: "Metallic Gun Metal", hex: "#2C3539" },
  { name: "Metallic Anthracite Gray", hex: "#383E42" },
  { name: "Matte Black", hex: "#0A0A0A" },
  { name: "Matte Gray", hex: "#3A3A3A" },
  { name: "Matte Light Gray", hex: "#B8B8B8" },
  { name: "Util Black", hex: "#0D0D0D" },
  { name: "Util Black Poly", hex: "#101010" },
  { name: "Util Dark Silver", hex: "#707070" },
  { name: "Util Silver", hex: "#C4C4C4" },
  { name: "Util Gun Metal", hex: "#2D373B" },
  { name: "Util Shadow Silver", hex: "#787878" },
  { name: "Worn Black", hex: "#1E1E1E" },
  { name: "Worn Graphite", hex: "#363636" },
  { name: "Worn Silver Gray", hex: "#8A8A8A" },
  { name: "Worn Silver", hex: "#B0B0B0" },
  { name: "Worn Blue Silver", hex: "#7D9EC0" },
  { name: "Worn Shadow Silver", hex: "#7A7A7A" },
  { name: "Metallic Red", hex: "#B22222" },
  { name: "Metallic Torino Red", hex: "#CC0000" },
  { name: "Metallic Formula Red", hex: "#E41B17" },
  { name: "Metallic Blaze Red", hex: "#FF4040" },
  { name: "Metallic Graceful Red", hex: "#9B111E" },
  { name: "Metallic Garnet Red", hex: "#831D1C" },
  { name: "Metallic Desert Red", hex: "#A52A2A" },
  { name: "Metallic Cabernet Red", hex: "#5D1F1E" },
  { name: "Metallic Candy Red", hex: "#D21404" },
  { name: "Metallic Sunrise Orange", hex: "#FF7F50" },
  { name: "Metallic Classic Gold", hex: "#D4AF37" },
  { name: "Metallic Orange", hex: "#E67E22" },
  { name: "Matte Red", hex: "#990000" },
  { name: "Matte Dark Red", hex: "#800000" },
  { name: "Matte Orange", hex: "#CC5500" },
  { name: "Matte Yellow", hex: "#FFDB58" },
  { name: "Util Red", hex: "#A91C1C" },
  { name: "Util Bright Red", hex: "#FF0000" },
  { name: "Util Garnet Red", hex: "#831D1C" },
  { name: "Worn Red", hex: "#A52A2A" },
  { name: "Worn Golden Red", hex: "#B32428" },
  { name: "Worn Dark Red", hex: "#800020" },
  { name: "Metallic Dark Green", hex: "#004225" },
  { name: "Metallic Racing Green", hex: "#0C4B33" },
  { name: "Metallic Sea Green", hex: "#2E8B57" },
  { name: "Metallic Olive Green", hex: "#556B2F" },
  { name: "Metallic Green", hex: "#228B22" },
  { name: "Metallic Gasoline Blue Green", hex: "#008080" },
  { name: "Matte Lime Green", hex: "#32CD32" },
  { name: "Util Dark Green", hex: "#4B5320" },
  { name: "Util Green", hex: "#008000" },
  { name: "Worn Dark Green", hex: "#2E8B57" },
  { name: "Worn Green", hex: "#008000" },
  { name: "Worn Sea Wash", hex: "#93E9BE" },
  { name: "Metallic Midnight Blue", hex: "#0F056B" },
  { name: "Metallic Dark Blue", hex: "#000080" },
  { name: "Metallic Saxony Blue", hex: "#1E90FF" },
  { name: "Metallic Blue", hex: "#0066CC" },
  { name: "Metallic Mariner Blue", hex: "#318CE7" },
  { name: "Metallic Harbor Blue", hex: "#005F6A" },
  { name: "Metallic Diamond Blue", hex: "#0F52BA" },
  { name: "Metallic Surf Blue", hex: "#00CED1" },
  { name: "Metallic Nautical Blue", hex: "#1A2B5F" },
  { name: "Metallic Bright Blue", hex: "#1E90FF" },
  { name: "Metallic Purple Blue", hex: "#8A2BE2" },
  { name: "Metallic Spinnaker Blue", hex: "#0A2240" },
  { name: "Metallic Ultra Blue", hex: "#0038A8" },
  { name: "Util Dark Blue", hex: "#000F5C" },
  { name: "Util Midnight Blue", hex: "#0A1A2A" },
  { name: "Util Blue", hex: "#1E90FF" },
  { name: "Util Sea Foam Blue", hex: "#87CEEB" },
  { name: "Util Lightning Blue", hex: "#0066CC" },
  { name: "Util Maui Blue Poly", hex: "#005F6A" },
  { name: "Util Bright Blue", hex: "#1E90FF" },
  { name: "Matte Dark Blue", hex: "#000080" },
  { name: "Matte Blue", hex: "#0000FF" },
  { name: "Matte Midnight Blue", hex: "#0F056B" },
  { name: "Worn Dark Blue", hex: "#000080" },
  { name: "Worn Blue", hex: "#0000FF" },
  { name: "Worn Light Blue", hex: "#87CEEB" },
  { name: "Metallic Taxi Yellow", hex: "#F5C300" },
  { name: "Metallic Race Yellow", hex: "#FFD700" },
  { name: "Metallic Bronze", hex: "#CD7F32" },
  { name: "Metallic Yellow Bird", hex: "#FFDB58" },
  { name: "Metallic Lime", hex: "#32CD32" },
  { name: "Metallic Champagne", hex: "#F7E7CE" },
  { name: "Metallic Pueblo Beige", hex: "#C19A6B" },
  { name: "Metallic Dark Ivory", hex: "#F2E6D6" },
  { name: "Metallic Choco Brown", hex: "#7B3F00" },
  { name: "Metallic Golden Brown", hex: "#996515" },
  { name: "Metallic Light Brown", hex: "#B87333" },
  { name: "Metallic Straw Beige", hex: "#E1C78F" },
  { name: "Metallic Moss Brown", hex: "#8B4513" },
  { name: "Metallic Biston Brown", hex: "#483C32" },
  { name: "Metallic Beechwood", hex: "#A67B5B" },
  { name: "Metallic Dark Beechwood", hex: "#8B4513" },
  { name: "Metallic Choco Orange", hex: "#D2691E" },
  { name: "Metallic Beach Sand", hex: "#F5DEB3" },
  { name: "Metallic Sun Bleeched Sand", hex: "#F3D9B1" },
  { name: "Metallic Cream", hex: "#FFFDD0" },
  { name: "Util Brown", hex: "#6F4E37" },
  { name: "Util Medium Brown", hex: "#80461B" },
  { name: "Util Light Brown", hex: "#AF6E4D" },
  { name: "Metallic White", hex: "#F5F5F5" },
  { name: "Metallic Frost White", hex: "#E1E1E1" },
  { name: "Worn Honey Beige", hex: "#F5DEB3" },
  { name: "Worn Brown", hex: "#8B4513" },
  { name: "Worn Dark Brown", hex: "#5D4037" },
  { name: "Worn Straw Beige", hex: "#E1C78F" },
  { name: "Brushed Steel", hex: "#B8B8B8" },
  { name: "Brushed Black Steel", hex: "#363636" },
  { name: "Brushed Aluminium", hex: "#A6A6A6" },
  { name: "Chrome", hex: "#E8E8E8" },
  { name: "Worn Off White", hex: "#EDEADE" },
  { name: "Util Off White", hex: "#F5F5F5" },
  { name: "Worn Orange", hex: "#FFA500" },
  { name: "Worn Light Orange", hex: "#F28500" },
  { name: "Metallic Securicor Green", hex: "#004225" },
  { name: "Worn Taxi Yellow", hex: "#F5C300" },
  { name: "Police Car Blue", hex: "#318CE7" },
  { name: "Matte Green", hex: "#008000" },
  { name: "Matte Brown", hex: "#6F4E37" },
  { name: "Worn Orange", hex: "#FFA500" },
  { name: "Matte White", hex: "#F5F5F5" },
  { name: "Worn White", hex: "#EAE6CA" },
  { name: "Worn Olive Army Green", hex: "#4B5320" },
  { name: "Pure White", hex: "#FFFFFF" },
  { name: "Hot Pink", hex: "#FF69B4" },
  { name: "Salmon Pink", hex: "#FF9999" },
  { name: "Metallic Vermillion Pink", hex: "#E0BFB8" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Green", hex: "#008000" },
  { name: "Metallic Black Blue", hex: "#0A1A2A" },
  { name: "Metallic Black Purple", hex: "#2E0854" },
  { name: "Metallic Black Red", hex: "#1A0000" },
  { name: "Hunter Green", hex: "#355E3B" },
  { name: "Metallic Purple", hex: "#800080" },
  { name: "Metallic V Dark Blue", hex: "#000F5C" },
  { name: "MODSHOP BLACK1", hex: "#0A0A0A" },
  { name: "Matte Purple", hex: "#800080" },
  { name: "Matte Dark Purple", hex: "#2E0854" },
  { name: "Metallic Lava Red", hex: "#B22222" },
  { name: "Matte Forest Green", hex: "#014421" },
  { name: "Matte Olive Drab", hex: "#6B8E23" },
  { name: "Matte Desert Brown", hex: "#C19A6B" },
  { name: "Matte Desert Tan", hex: "#D2B48C" },
  { name: "Matte Foilage Green", hex: "#4B5320" },
  { name: "DEFAULT ALLOY COLOR", hex: "#808080" },
  { name: "Epsilon Blue", hex: "#1E90FF" },
  { name: "Pure Gold", hex: "#FFD700" },
  { name: "Brushed Gold", hex: "#D4AF37" },
  { name: "Olive", hex: "#808000" },
  { name: "Copper", hex: "#B87333" },
  { name: "Other", hex: "#A9A9A9" },
  { name: "Dark Grey", hex: "#A9A9A9" },
  { name: "Magnetic Black", hex: "#1C1C1C" },
  { name: "Polar White", hex: "#F0F0F0" },
  { name: "Chestnut Brown", hex: "#954535" },
  { name: "Saddle Brown", hex: "#8B4513" },
  { name: "Black Obsidian", hex: "#0A0A0A" },
  { name: "Royal Blue", hex: "#0038A8" },
  { name: "Blue Metallic", hex: "#0066CC" },
  { name: "Dark Graphite Metallic", hex: "#383E42" },
  { name: "Cream", hex: "#FFFDD0" },
  { name: "Pearl White", hex: "#F8F8FF" },
  { name: "Silver Lining Metallic", hex: "#D4D4D4" },
  { name: "Moonlight Blue Metallic", hex: "#78B4C6" },
  { name: "Oolong Gray Metallic", hex: "#757575" },
  { name: "Florett Silver Metallic", hex: "#C0C0C0" },
  { name: "Alpine White", hex: "#F5F5F5" },
  { name: "Drak Gray", hex: "#585858" },
  { name: "Diamond Silver Metallic", hex: "#A6A6A6" },
  { name: "Mineral Gray Metallic", hex: "#4C4C4C" },
  { name: "Coral Red", hex: "#FF4040" },
  { name: "Jet Black Metallic", hex: "#0A0A0A" },
  { name: "Nero Puro (black)", hex: "#000000" },
  { name: "Red/black", hex: "#800000" },
  { name: "Gray/black", hex: "#383838" },
  { name: "Pearl White Tri-coat", hex: "#F8F8FF" },
  { name: "Sandstorm Cream", hex: "#F7E7CE" },
  { name: "Slate Metallic", hex: "#708090" },
  { name: "Jet Black", hex: "#0A0A0A" },
  { name: "Red/brown", hex: "#800020" },
  { name: "Quicksilver Metallic", hex: "#A6A6A6" },
  { name: "Dark Gray", hex: "#A9A9A9" },
  { name: "Granite Crystal Metallic", hex: "#383E42" },
  { name: "Bianco/white", hex: "#FFFFFF" },
  { name: "Dark Gray-brown", hex: "#483C32" },
  { name: "Cattle Tan", hex: "#D2B48C" },
  { name: "Metropolitan Gray Mica", hex: "#4C4C4C" },
  { name: "Polished Metal Metallic", hex: "#B8B8B8" },
  { name: "Night Blue Metallic", hex: "#0F056B" },
  { name: "Cornsilk Beige", hex: "#F5F5DC" },
  { name: "Stormy Sea Blue", hex: "#005F6A" },
  { name: "Calcite White", hex: "#F5F5F5" },
  { name: "Blue Onyx", hex: "#0F52BA" },
  { name: "Stone", hex: "#8B8B8B" },
  { name: "Mountain Gray Metallic", hex: "#4C4C4C" },
  { name: "Shadow Black", hex: "#0A0A0A" },
  { name: "Charcoal Black", hex: "#36454F" },
  { name: "Ibis White", hex: "#F5F5F5" },
  { name: "Cajun Red Tintcoat", hex: "#800020" },
  { name: "Crystal Black Silica", hex: "#0A0A0A" },
  { name: "Titan Black", hex: "#0A0A0A" },
  { name: "Snow White Pearl", hex: "#F8F8FF" },
  { name: "Barcelona Red Metallic", hex: "#800020" },
  { name: "Idridium Gray Metallic", hex: "#4C4C4C" },
  { name: "Aurora Black", hex: "#0A0A0A" },
  { name: "Metallic Slate Blue", hex: "#6A5ACD" },
  { name: "Twilight Black", hex: "#0A0A0A" },
  { name: "Ingot Silver", hex: "#C0C0C0" },
  { name: "Medium Light Stone", hex: "#B8B8B8" },
  { name: "White Diamond Pearl", hex: "#F8F8FF" },
  { name: "Soul Red Crystal Metallic", hex: "#800020" },
  { name: "Gun Metallic Gray", hex: "#2C3539" },
  { name: "Crystal Black Pearl", hex: "#0A0A0A" },
  { name: "Titanium Flash Mica", hex: "#B8B8B8" },
  { name: "Blue Granite Metallic", hex: "#0F52BA" },
  { name: "Scarlet Ember", hex: "#800020" },
  { name: "Glacier White Tr-coat", hex: "#F8F8FF" },
  { name: "Monsoon Gray Metallic", hex: "#4C4C4C" },
  { name: "Billet Argento (silver)", hex: "#C0C0C0" },
  { name: "Black/gray", hex: "#383838" },
  { name: "Graphite Gray Metallic", hex: "#383E42" },
  { name: "Desert Sand", hex: "#EDC9AF" },
  { name: "Avatar Blue Metallic", hex: "#0F52BA" },
  { name: "Deep Sea Blue Metallic", hex: "#000080" },
  { name: "Ingot Silver Metallic", hex: "#C0C0C0" },
  { name: "Prairie Pearl", hex: "#F8F8FF" },
  { name: "Dark Cherry Pearl", hex: "#800020" },
  { name: "Deep Auburn Pearlcoat", hex: "#800020" },
  { name: "Jeep Brown", hex: "#6F4E37" },
  { name: "Candy White", hex: "#F5F5F5" },
  { name: "Light Gray", hex: "#D3D3D3" },
  { name: "White Opal", hex: "#F8F8FF" },
  { name: "Titanium Gray", hex: "#878681" },
  { name: "Oxford White", hex: "#F5F5F5" },
  { name: "Earth Gray", hex: "#4C4C4C" },
  { name: "Monsoon Gray", hex: "#4C4C4C" },
  { name: "Black/brown", hex: "#483C32" },
  { name: "Diamond White Metallic", hex: "#F8F8FF" },
  { name: "Fuji White", hex: "#F5F5F5" },
  { name: "Almond Brown", hex: "#AF6E4D" },
  { name: "Satin White", hex: "#EAE6CA" },
  { name: "Winter White", hex: "#F5F5F5" },
  { name: "Rooftop Gray Metallic", hex: "#4C4C4C" },
  { name: "Kodiak Brown Metallic", hex: "#6F4E37" },
  { name: "Espresso", hex: "#4C3A2F" },
  { name: "Carmine Red", hex: "#800020" },
  { name: "Brilliant Black", hex: "#0A0A0A" },
  { name: "Brilliant Red", hex: "#800020" },
  { name: "Galaxy Gray Metallic", hex: "#4C4C4C" },
  { name: "Blue Velvet Metallic", hex: "#000080" },
  { name: "Bright White Clearcoat", hex: "#F5F5F5" },
  { name: "Bali Blue", hex: "#005F6A" },
  { name: "Saffrano Orange/black", hex: "#FFA500" },
  { name: "Bellanova White", hex: "#F5F5F5" },
  { name: "Parchment Leather/beige", hex: "#F5F5DC" },
  { name: "Daytona Gray Pearl", hex: "#4C4C4C" },
  { name: "Midnight Red Pearl", hex: "#800020" },
  { name: "Ruby Red Clearcoat", hex: "#800020" },
  { name: "Bellanova White Pearl", hex: "#F8F8FF" },
  { name: "Umber Leather/brown", hex: "#6F4E37" },
  { name: "Bianco Perla", hex: "#F8F8FF" },
  { name: "Super Black", hex: "#0A0A0A" },
  { name: "Magnetic Gray", hex: "#4C4C4C" },
  { name: "Black Sapphire Metallic", hex: "#0A0A0A" },
  { name: "Opal Sage Metallic", hex: "#93E9BE" },
  { name: "Iridium Silver Metallic", hex: "#C0C0C0" },
  { name: "Obsidian Blue Pearl", hex: "#0F056B" },
  { name: "White Diamond Tricoat", hex: "#F8F8FF" },
  { name: "White Silver Metallic", hex: "#F5F5F5" },
  { name: "White Sand Tri-coat Metallic", hex: "#F7E7CE" },
  { name: "Quartz Brown Metallic", hex: "#6F4E37" },
  { name: "Brilliant Silver Metallic", hex: "#C0C0C0" },
  { name: "Triple Yellow", hex: "#FFD700" },
  { name: "Deep Black Pearl", hex: "#0A0A0A" },
  { name: "Silver Ice Metallic", hex: "#C0C0C0" },
  { name: "Almond Beige", hex: "#F5F5DC" },
  { name: "Diamond White", hex: "#F8F8FF" },
  { name: "Monza Silver Metallic", hex: "#C0C0C0" },
  { name: "Sterling Gray Metallic", hex: "#4C4C4C" },
  { name: "Billet Metallic", hex: "#B8B8B8" },
  { name: "Kodiak Brown", hex: "#6F4E37" },
  { name: "Graphite Blue", hex: "#0F52BA" },
  { name: "Dark Blue", hex: "#000080" },
  { name: "Maroon", hex: "#800020" },
  { name: "Beige/black", hex: "#F5F5DC" },
  { name: "Stone Gray", hex: "#8B8B8B" },
  { name: "Asgard Gray", hex: "#4C4C4C" },
  { name: "Graphite", hex: "#383E42" },
  { name: "Aluminum Metallic Mica", hex: "#A6A6A6" },
  { name: "Eminent White Pearl", hex: "#F8F8FF" },
  { name: "Jet Black Mica", hex: "#0A0A0A" },
  { name: "Clark Cloth", hex: "#F5F5F5" },
  { name: "Ruby Red Metallic", hex: "#800020" },
  { name: "Caspian Blue", hex: "#005F6A" },
  { name: "Dark Currant/brown", hex: "#483C32" },
  { name: "Crimson Red Pearl", hex: "#800020" },
  { name: "Boston Red", hex: "#800020" },
  { name: "Blue Graphite", hex: "#0F52BA" },
  { name: "Santorini Black", hex: "#0A0A0A" },
  { name: "Nebula Gray Pearl", hex: "#4C4C4C" },
  { name: "Rioja Red", hex: "#800020" },
  { name: "Midnight Black", hex: "#0A0A0A" },
  { name: "Ember Black", hex: "#0A0A0A" },
  { name: "Crystal Red Tintcoat", hex: "#800020" },
  { name: "Snow Pearl White", hex: "#F8F8FF" },
  { name: "Tinted Bronze", hex: "#CD7F32" },
  { name: "Cuvee Silver Metallic", hex: "#C0C0C0" },
  { name: "Gun Metallic", hex: "#2C3539" },
  { name: "Wr Blue Pearl", hex: "#005F6A" },
  { name: "Champagne Metallic", hex: "#F7E7CE" },
  { name: "Silver Metallic", hex: "#C0C0C0" },
  { name: "Umbria Twilight Metallic", hex: "#4C4C4C" },
  { name: "Ivory Pearl White", hex: "#F8F8FF" },
  { name: "Tan/wheat", hex: "#D2B48C" },
  { name: "Red & Black", hex: "#800020" },
  { name: "Frost White Pearl", hex: "#F8F8FF" },
  { name: "Phantom Black Pearl", hex: "#0A0A0A" },
  { name: "Mythos Black Metallic", hex: "#0A0A0A" },
  { name: "Brilliant Black Crystal Pearl", hex: "#0A0A0A" },
  { name: "Midnight Mocha Metallic", hex: "#483C32" },
  { name: "Aspen White Pearl", hex: "#F8F8FF" },
  { name: "Sun Fusion", hex: "#FFA500" },
  { name: "Dark Charcoal", hex: "#333333" },
  { name: "Atlas Beige", hex: "#F5F5DC" },
  { name: "Palladium Silver Metallic", hex: "#C0C0C0" },
  { name: "Silk Beige", hex: "#F5F5DC" },
  { name: "Selenite Gray Metallic", hex: "#4C4C4C" },
  { name: "Estoril Blue Metallic", hex: "#005F6A" },
  { name: "Cosmos Black Metallic", hex: "#0A0A0A" },
  { name: "Sahara Beige", hex: "#F5F5DC" },
  { name: "White Platinum", hex: "#F5F5F5" },
  { name: "Lunar Gray Metallic", hex: "#4C4C4C" },
  { name: "Charcoal W/red Stitching", hex: "#333333" },
  { name: "Bianco Perla (pearl White Tricoat)", hex: "#F8F8FF" },
  { name: "Avorio (ivory)", hex: "#FFFFF0" },
  { name: "Olive Green", hex: "#808000" },
  { name: "Ivory", hex: "#FFFFF0" },
  { name: "Obsidian Black Metallic", hex: "#0A0A0A" },
  { name: "Classic Silver Metallic", hex: "#C0C0C0" },
  { name: "Deep Cherry Pearl", hex: "#800020" },
  { name: "Slate Gray", hex: "#708090" },
  { name: "Desert Rock Metallic", hex: "#C19A6B" },
  { name: "Blu Passione Mica", hex: "#005F6A" },
  { name: "Cuoio", hex: "#D2B48C" },
  { name: "Starfire Pearl", hex: "#F8F8FF" },
  { name: "Alien Metallic", hex: "#4C4C4C" },
  { name: "Reflex Silver Metallic", hex: "#C0C0C0" },
  { name: "Magnetic Gray Metallic", hex: "#4C4C4C" },
  { name: "Victory Red", hex: "#800020" },
  { name: "White Orchid Pearl", hex: "#F8F8FF" },
  { name: "Red Candy Metallic", hex: "#800020" },
  { name: "White Platinum Metallic", hex: "#F5F5F5" },
  { name: "Black Metallic", hex: "#0A0A0A" },
  { name: "Dark Gray Metallic", hex: "#4C4C4C" },
  { name: "Onyx Black", hex: "#0A0A0A" },
  { name: "Lotus Gray Metallic", hex: "#4C4C4C" },
  { name: "Meteor Gray Mica", hex: "#4C4C4C" },
  { name: "Bamboo Pearl", hex: "#F5F5DC" },
  { name: "Magnetic Metallic", hex: "#4C4C4C" },
  { name: "Black Raven", hex: "#0A0A0A" },
  { name: "Pyrite Mica", hex: "#B87333" },
  { name: "Sand Beige", hex: "#F5F5DC" },
  { name: "Wicked White", hex: "#F5F5F5" },
  { name: "Jupiter Red", hex: "#800020" },
  { name: "Gloss Black", hex: "#0A0A0A" },
  { name: "Graphite Luster Metallic", hex: "#383E42" },
  { name: "Black Sapphire Pearl", hex: "#0A0A0A" },
  { name: "Light White", hex: "#F5F5F5" },
  { name: "Carbon Black", hex: "#0A0A0A" },
  { name: "Metal Bronze Metallic", hex: "#B87333" },
  { name: "Steel Black", hex: "#262626" },
  { name: "Coast Blue Pearl", hex: "#005F6A" },
  { name: "Taffeta White", hex: "#F5F5F5" },
  { name: "Yulong White", hex: "#F5F5F5" },
  { name: "Ash Black Mica", hex: "#0A0A0A" },
  { name: "Frozen White", hex: "#F5F5F5" },
  { name: "Smoky Granite Mica", hex: "#4C4C4C" },
  { name: "Becketts Black", hex: "#0A0A0A" },
  { name: "Bright Silver Metallic", hex: "#C0C0C0" },
  { name: "Graystone", hex: "#4C4C4C" },
  { name: "Sunset Bronze Mica", hex: "#CD7F32" },
  { name: "Cosmic Blue", hex: "#005F6A" },
  { name: "Sparkling Black Mica", hex: "#0A0A0A" },
  { name: "Starlight Black Mica", hex: "#0A0A0A" },
  { name: "Off-black", hex: "#383838" },
  { name: "Summit White", hex: "#F5F5F5" },
  { name: "Black Opal Mica", hex: "#0A0A0A" },
  { name: "Aspen Pearl", hex: "#F8F8FF" },
  { name: "Titanium Silver Metallic", hex: "#C0C0C0" },
  { name: "Majestic White Pearl", hex: "#F8F8FF" },
  { name: "Java/dark Brown", hex: "#483C32" },
  { name: "Steel Blue Metallic", hex: "#4682B4" },
  { name: "Titan Black/artgray", hex: "#0A0A0A" },
  { name: "Moonlight White", hex: "#F5F5F5" },
  { name: "Modern Steel Metallic", hex: "#4C4C4C" },
  { name: "Blue Onyx Pearl Metallic", hex: "#0F52BA" },
  { name: "Dark Charcoal Pearl", hex: "#333333" },
];

export const COULEURS3 = [
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Metallic Black", hex: "#0A0A0A" },
  { name: "Metallic Graphite Black", hex: "#1A1A1A" },
  { name: "Metallic Black Steal", hex: "#0A0A0A" }, // Similaire à Metallic Black
  { name: "Metallic Dark Silver", hex: "#6C6C6C" },
  { name: "Metallic Silver", hex: "#A8A8A8" },
  { name: "Metallic Blue Silver", hex: "#7D9EC0" },
  { name: "Metallic Steel Gray", hex: "#6F7278" },
  { name: "Metallic Shadow Silver", hex: "#7B7D7D" },
  { name: "Metallic Stone Silver", hex: "#8B8C89" },
  { name: "Metallic Midnight Silver", hex: "#4E545B" },
  { name: "Metallic Gun Metal", hex: "#2C3539" },
  { name: "Metallic Anthracite Gray", hex: "#383E42" },
  { name: "Matte Black", hex: "#121212" },
  { name: "Matte Gray", hex: "#6A6868" },
  { name: "Matte Light Gray", hex: "#A0A0A0" },
  { name: "Util Black", hex: "#0A0A0A" },
  { name: "Util Black Poly", hex: "#0A0A0A" }, // Similaire à Util Black
  { name: "Util Dark silver", hex: "#6C6C6C" },
  { name: "Util Silver", hex: "#A8A8A8" },
  { name: "Util Gun Metal", hex: "#2C3539" },
  { name: "Util Shadow Silver", hex: "#7B7D7D" },
  { name: "Worn Black", hex: "#1B1B1B" },
  { name: "Worn Graphite", hex: "#2F2F2F" },
  { name: "Worn Silver Gray", hex: "#8C8C8C" },
  { name: "Worn Silver", hex: "#C0C0C0" },
  { name: "Worn Blue Silver", hex: "#7D9EC0" },
  { name: "Worn Shadow Silver", hex: "#7B7D7D" },
  { name: "Metallic Red", hex: "#C00000" },
  { name: "Metallic Torino Red", hex: "#B22222" },
  { name: "Metallic Formula Red", hex: "#D40000" },
  { name: "Metallic Blaze Red", hex: "#FF2400" },
  { name: "Metallic Graceful Red", hex: "#D10047" },
  { name: "Metallic Garnet Red", hex: "#831D1D" },
  { name: "Metallic Desert Red", hex: "#A52A2A" },
  { name: "Metallic Cabernet Red", hex: "#5D1F1F" },
  { name: "Metallic Candy Red", hex: "#FF0800" },
  { name: "Metallic Sunrise Orange", hex: "#FF7F50" },
  { name: "Metallic Classic Gold", hex: "#D4AF37" },
  { name: "Metallic Orange", hex: "#FF8C00" },
  { name: "Matte Red", hex: "#A00000" },
  { name: "Matte Dark Red", hex: "#800000" },
  { name: "Matte Orange", hex: "#CC5500" },
  { name: "Matte Yellow", hex: "#CCCC00" },
  { name: "Util Red", hex: "#A00000" },
  { name: "Util Bright Red", hex: "#D40000" },
  { name: "Util Garnet Red", hex: "#831D1D" },
  { name: "Worn Red", hex: "#A52A2A" },
  { name: "Worn Golden Red", hex: "#B87333" },
  { name: "Worn Dark Red", hex: "#800000" },
  { name: "Metallic Dark Green", hex: "#023020" },
  { name: "Metallic Racing Green", hex: "#004225" },
  { name: "Metallic Sea Green", hex: "#2E8B57" },
  { name: "Metallic Olive Green", hex: "#556B2F" },
  { name: "Metallic Green", hex: "#008000" },
  { name: "Metallic Gasoline Blue Green", hex: "#228B22" },
  { name: "Matte Lime Green", hex: "#32CD32" },
  { name: "Util Dark Green", hex: "#023020" },
  { name: "Util Green", hex: "#008000" },
  { name: "Worn Dark Green", hex: "#013220" },
  { name: "Worn Green", hex: "#008000" },
  { name: "Worn Sea Wash", hex: "#2E8B57" },
  { name: "Metallic Midnight Blue", hex: "#191970" },
  { name: "Metallic Dark Blue", hex: "#00008B" },
  { name: "Metallic Saxony Blue", hex: "#4682B4" },
  { name: "Metallic Blue", hex: "#0000FF" },
  { name: "Metallic Mariner Blue", hex: "#1E90FF" },
  { name: "Metallic Harbor Blue", hex: "#4169E1" },
  { name: "Metallic Diamond Blue", hex: "#1E90FF" },
  { name: "Metallic Surf Blue", hex: "#00BFFF" },
  { name: "Metallic Nautical Blue", hex: "#1E90FF" },
  { name: "Metallic Bright Blue", hex: "#0096FF" },
  { name: "Metallic Purple Blue", hex: "#8A2BE2" },
  { name: "Metallic Spinnaker Blue", hex: "#00BFFF" },
  { name: "Metallic Ultra Blue", hex: "#0000FF" },
  { name: "Util Dark Blue", hex: "#00008B" },
  { name: "Util Midnight Blue", hex: "#191970" },
  { name: "Util Blue", hex: "#0000FF" },
  { name: "Util Sea Foam Blue", hex: "#00BFFF" },
  { name: "Util Lightning blue", hex: "#1E90FF" },
  { name: "Util Maui Blue Poly", hex: "#4169E1" },
  { name: "Util Bright Blue", hex: "#0096FF" },
  { name: "Matte Dark Blue", hex: "#00008B" },
  { name: "Matte Blue", hex: "#0000FF" },
  { name: "Matte Midnight Blue", hex: "#191970" },
  { name: "Worn Dark blue", hex: "#00008B" },
  { name: "Worn Blue", hex: "#0000FF" },
  { name: "Worn Light blue", hex: "#ADD8E6" },
  { name: "Metallic Taxi Yellow", hex: "#FFD700" },
  { name: "Metallic Race Yellow", hex: "#FFD700" },
  { name: "Metallic Bronze", hex: "#CD7F32" },
  { name: "Metallic Yellow Bird", hex: "#FFD700" },
  { name: "Metallic Lime", hex: "#00FF00" },
  { name: "Metallic Champagne", hex: "#F7E7CE" },
  { name: "Metallic Pueblo Beige", hex: "#D2B48C" },
  { name: "Metallic Dark Ivory", hex: "#F2E6D6" },
  { name: "Metallic Choco Brown", hex: "#D2691E" },
  { name: "Metallic Golden Brown", hex: "#996515" },
  { name: "Metallic Light Brown", hex: "#B5651D" },
  { name: "Metallic Straw Beige", hex: "#F5DEB3" },
  { name: "Metallic Moss Brown", hex: "#8A9A5B" },
  { name: "Metallic Biston Brown", hex: "#967117" },
  { name: "Metallic Beechwood", hex: "#C19A6B" },
  { name: "Metallic Dark Beechwood", hex: "#8B7355" },
  { name: "Metallic Choco Orange", hex: "#D2691E" },
  { name: "Metallic Beach Sand", hex: "#F5DEB3" },
  { name: "Metallic Sun Bleeched Sand", hex: "#F5DEB3" },
  { name: "Metallic Cream", hex: "#FFFDD0" },
  { name: "Util Brown", hex: "#964B00" },
  { name: "Util Medium Brown", hex: "#80461B" },
  { name: "Util Light Brown", hex: "#B5651D" },
  { name: "Metallic White", hex: "#FFFFFF" },
  { name: "Metallic Frost White", hex: "#F5F5F5" },
  { name: "Worn Honey Beige", hex: "#F5DEB3" },
  { name: "Worn Brown", hex: "#964B00" },
  { name: "Worn Dark Brown", hex: "#654321" },
  { name: "Worn straw beige", hex: "#F5DEB3" },
  { name: "Brushed Steel", hex: "#6F7278" },
  { name: "Brushed Black steel", hex: "#2F2F2F" },
  { name: "Brushed Aluminium", hex: "#A8A8A8" },
  { name: "Chrome", hex: "#E8E8E8" },
  { name: "Worn Off White", hex: "#F5F5F5" },
  { name: "Util Off White", hex: "#F5F5F5" },
  { name: "Worn Orange", hex: "#FF8C00" },
  { name: "Worn Light Orange", hex: "#FFA500" },
  { name: "Metallic Securicor Green", hex: "#008000" },
  { name: "Worn Taxi Yellow", hex: "#FFD700" },
  { name: "police car blue", hex: "#0000FF" },
  { name: "Matte Green", hex: "#008000" },
  { name: "Matte Brown", hex: "#654321" },
  { name: "Matte White", hex: "#FFFFFF" },
  { name: "Worn White", hex: "#F5F5F5" },
  { name: "Worn Olive Army Green", hex: "#556B2F" },
  { name: "Pure White", hex: "#FFFFFF" },
  { name: "Hot Pink", hex: "#FF69B4" },
  { name: "Salmon pink", hex: "#FA8072" },
  { name: "Metallic Vermillion Pink", hex: "#FF5349" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Green", hex: "#008000" },
  { name: "Mettalic Black Blue", hex: "#000033" },
  { name: "Metallic Black Purple", hex: "#330033" },
  { name: "Metallic Black Red", hex: "#330000" },
  { name: "hunter green", hex: "#355E3B" },
  { name: "Metallic Purple", hex: "#800080" },
  { name: "Metaillic V Dark Blue", hex: "#000033" },
  { name: "MODSHOP BLACK1", hex: "#000000" },
  { name: "Matte Purple", hex: "#800080" },
  { name: "Matte Dark Purple", hex: "#4B0082" },
  { name: "Metallic Lava Red", hex: "#FF4500" },
  { name: "Matte Forest Green", hex: "#228B22" },
  { name: "Matte Olive Drab", hex: "#6B8E23" },
  { name: "Matte Desert Brown", hex: "#8B4513" },
  { name: "Matte Desert Tan", hex: "#D2B48C" },
  { name: "Matte Foilage Green", hex: "#6B8E23" },
  { name: "DEFAULT ALLOY COLOR", hex: "#A8A8A8" },
  { name: "Epsilon Blue", hex: "#1E90FF" },
  { name: "Pure Gold", hex: "#FFD700" },
  { name: "Brushed Gold", hex: "#D4AF37" },
  { name: "Olive", hex: "#808000" },
  { name: "Copper", hex: "#B87333" },
  { name: "Other", hex: "#CCCCCC" }, // Générique pour "Autre"
  { name: "Dark Grey", hex: "#A9A9A9" },
  { name: "Magnetic Black", hex: "#0A0A0A" },
  { name: "Polar White", hex: "#F5F5F5" },
  { name: "Chestnut Brown", hex: "#954535" },
  { name: "Saddle Brown", hex: "#8B4513" },
  { name: "Black Obsidian", hex: "#000000" },
  { name: "Royal Blue", hex: "#4169E1" },
  { name: "Blue Metallic", hex: "#0000FF" },
  { name: "Dark Graphite Metallic", hex: "#383E42" },
  { name: "Cream", hex: "#FFFDD0" },
  { name: "Pearl White", hex: "#F5F5F5" },
  { name: "Silver Lining Metallic", hex: "#C0C0C0" },
  { name: "Moonlight Blue Metallic", hex: "#1E90FF" },
  { name: "Oolong Gray Metallic", hex: "#6F7278" },
  { name: "Florett Silver Metallic", hex: "#A8A8A8" },
  { name: "Alpine White", hex: "#FFFFFF" },
  { name: "Drak Gray", hex: "#A9A9A9" }, // Typo probable pour "Dark Gray"
  { name: "Diamond Silver Metallic", hex: "#C0C0C0" },
  { name: "Mineral Gray Metallic", hex: "#6F7278" },
  { name: "Coral Red", hex: "#FF7F50" },
  { name: "Jet Black Metallic", hex: "#000000" },
  { name: "Nero Puro (black)", hex: "#000000" },
  { name: "Red/black", hex: "#FF0000" }, // Bicolore
  { name: "Gray/black", hex: "#808080" }, // Bicolore
  { name: "Pearl White Tri-coat", hex: "#F5F5F5" },
  { name: "Sandstorm Cream", hex: "#F5DEB3" },
  { name: "Slate Metallic", hex: "#708090" },
  { name: "Jet Black", hex: "#000000" },
  { name: "Red/brown", hex: "#A52A2A" }, // Bicolore
  { name: "Quicksilver Metallic", hex: "#A8A8A8" },
  { name: "Dark Gray", hex: "#A9A9A9" },
  { name: "Granite Crystal Metallic", hex: "#383E42" },
  { name: "Bianco/white", hex: "#FFFFFF" },
  { name: "Dark Gray-brown", hex: "#654321" },
  { name: "Cattle Tan", hex: "#D2B48C" },
  { name: "Metropolitan Gray Mica", hex: "#6F7278" },
  { name: "Polished Metal Metallic", hex: "#A8A8A8" },
  { name: "Night Blue Metallic", hex: "#000033" },
  { name: "Cornsilk Beige", hex: "#FFF8DC" },
  { name: "Stormy Sea Blue", hex: "#4682B4" },
  { name: "Calcite White", hex: "#FFFFFF" },
  { name: "Blue Onyx", hex: "#1E90FF" },
  { name: "Stone", hex: "#8B8C89" },
  { name: "Mountain Gray Metallic", hex: "#6F7278" },
  { name: "Shadow Black", hex: "#000000" },
  { name: "Charcoal Black", hex: "#36454F" },
  { name: "Ibis White", hex: "#FFFFFF" },
  { name: "Cajun Red Tintcoat", hex: "#D40000" },
  { name: "Crystal Black Silica", hex: "#000000" },
  { name: "Titan Black", hex: "#000000" },
  { name: "Snow White Pearl", hex: "#F5F5F5" },
  { name: "Barcelona Red Metallic", hex: "#D40000" },
  { name: "Idridium Gray Metallic", hex: "#6F7278" },
  { name: "Aurora Black", hex: "#000000" },
  { name: "Metallic Slate Blue", hex: "#708090" },
  { name: "Twilight Black", hex: "#000000" },
  { name: "Ingot Silver", hex: "#C0C0C0" },
  { name: "Medium Light Stone", hex: "#8B8C89" },
  { name: "White Diamond Pearl", hex: "#F5F5F5" },
  { name: "Soul Red Crystal Metallic", hex: "#D40000" },
  { name: "Gun Metallic Gray", hex: "#2C3539" },
  { name: "Crystal Black Pearl", hex: "#000000" },
  { name: "Titanium Flash Mica", hex: "#A8A8A8" },
  { name: "Blue Granite Metallic", hex: "#1E90FF" },
  { name: "Scarlet Ember", hex: "#FF2400" },
  { name: "Glacier White Tr-coat", hex: "#F5F5F5" },
  { name: "Monsoon Gray Metallic", hex: "#6F7278" },
  { name: "Billet Argento (silver)", hex: "#C0C0C0" },
  { name: "Black/gray", hex: "#000000" }, // Bicolore
  { name: "Graphite Gray Metallic", hex: "#383E42" },
  { name: "Desert Sand", hex: "#EDC9AF" },
  { name: "Avatar Blue Metallic", hex: "#1E90FF" },
  { name: "Deep Sea Blue Metallic", hex: "#00008B" },
  { name: "Ingot Silver Metallic", hex: "#C0C0C0" },
  { name: "Prairie Pearl", hex: "#F5F5F5" },
  { name: "Dark Cherry Pearl", hex: "#800000" },
  { name: "Deep Auburn Pearlcoat", hex: "#A52A2A" },
  { name: "Jeep Brown", hex: "#654321" },
  { name: "Candy White", hex: "#FFFFFF" },
  { name: "Light Gray", hex: "#D3D3D3" },
  { name: "White Opal", hex: "#F5F5F5" },
  { name: "Titanium Gray", hex: "#A8A8A8" },
  { name: "Oxford White", hex: "#FFFFFF" },
  { name: "Earth Gray", hex: "#6F7278" },
  { name: "Monsoon Gray", hex: "#6F7278" },
  { name: "Black/brown", hex: "#000000" }, // Bicolore
  { name: "Diamond White Metallic", hex: "#F5F5F5" },
  { name: "Fuji White", hex: "#FFFFFF" },
  { name: "Almond Brown", hex: "#D2B48C" },
  { name: "Satin White", hex: "#F5F5F5" },
  { name: "Winter White", hex: "#F5F5F5" },
  { name: "Rooftop Gray Metallic", hex: "#6F7278" },
  { name: "Kodiak Brown Metallic", hex: "#654321" },
  { name: "Espresso", hex: "#4E3524" },
  { name: "Carmine Red", hex: "#D40047" },
  { name: "Brilliant Black", hex: "#000000" },
  { name: "Brilliant Red", hex: "#D40000" },
  { name: "Galaxy Gray Metallic", hex: "#6F7278" },
  { name: "Blue Velvet Metallic", hex: "#00008B" },
  { name: "Bright White Clearcoat", hex: "#FFFFFF" },
  { name: "Bali Blue", hex: "#1E90FF" },
  { name: "Saffrano Orange/black", hex: "#FF8C00" }, // Bicolore
  { name: "Bellanova White", hex: "#FFFFFF" },
  { name: "Parchment Leather/beige", hex: "#F5DEB3" },
  { name: "Daytona Gray Pearl", hex: "#6F7278" },
  { name: "Midnight Red Pearl", hex: "#800000" },
  { name: "Ruby Red Clearcoat", hex: "#D40000" },
  { name: "Bellanova White Pearl", hex: "#F5F5F5" },
  { name: "Umber Leather/brown", hex: "#654321" },
  { name: "Bianco Perla", hex: "#F5F5F5" },
  { name: "Super Black", hex: "#000000" },
  { name: "Magnetic Gray", hex: "#6F7278" },
  { name: "Black Sapphire Metallic", hex: "#000033" },
  { name: "Opal Sage Metallic", hex: "#8A9A5B" },
  { name: "Iridium Silver Metallic", hex: "#C0C0C0" },
  { name: "Obsidian Blue Pearl", hex: "#000033" },
  { name: "White Diamond Tricoat", hex: "#F5F5F5" },
  { name: "White Silver Metallic", hex: "#F5F5F5" },
  { name: "White Sand Tri-coat Metallic", hex: "#F5F5F5" },
  { name: "Quartz Brown Metallic", hex: "#654321" },
  { name: "Brilliant Silver Metallic", hex: "#C0C0C0" },
  { name: "Triple Yellow", hex: "#FFD700" },
  { name: "Deep Black Pearl", hex: "#000000" },
  { name: "Silver Ice Metallic", hex: "#C0C0C0" },
  { name: "Almond Beige", hex: "#D2B48C" },
  { name: "Diamond White", hex: "#F5F5F5" },
  { name: "Monza Silver Metallic", hex: "#C0C0C0" },
  { name: "Sterling Gray Metallic", hex: "#6F7278" },
  { name: "Billet Metallic", hex: "#A8A8A8" },
  { name: "Kodiak Brown", hex: "#654321" },
  { name: "Graphite Blue", hex: "#1E90FF" },
  { name: "Dark Blue", hex: "#00008B" },
  { name: "Maroon", hex: "#800000" },
  { name: "Beige/black", hex: "#F5DEB3" }, // Bicolore
  { name: "Stone Gray", hex: "#8B8C89" },
  { name: "Asgard Gray", hex: "#6F7278" },
  { name: "Graphite", hex: "#383E42" },
  { name: "Aluminum Metallic Mica", hex: "#A8A8A8" },
  { name: "Eminent White Pearl", hex: "#F5F5F5" },
  { name: "Jet Black Mica", hex: "#000000" },
  { name: "Clark Cloth", hex: "#CCCCCC" }, // Générique
  { name: "Ruby Red Metallic", hex: "#D40000" },
  { name: "Caspian Blue", hex: "#1E90FF" },
  { name: "Dark Currant/brown", hex: "#654321" },
  { name: "Crimson Red Pearl", hex: "#D40047" },
  { name: "Boston Red", hex: "#D40000" },
  { name: "Blue Graphite", hex: "#1E90FF" },
  { name: "Santorini Black", hex: "#000000" },
  { name: "Nebula Gray Pearl", hex: "#6F7278" },
  { name: "Rioja Red", hex: "#800000" },
  { name: "Midnight Black", hex: "#000000" },
  { name: "Ember Black", hex: "#000000" },
  { name: "Crystal Red Tintcoat", hex: "#D40000" },
  { name: "Snow Pearl White", hex: "#F5F5F5" },
  { name: "Tinted Bronze", hex: "#CD7F32" },
  { name: "Cuvee Silver Metallic", hex: "#C0C0C0" },
  { name: "Gun Metallic", hex: "#2C3539" },
  { name: "Wr Blue Pearl", hex: "#1E90FF" },
  { name: "Champagne Metallic", hex: "#F7E7CE" },
  { name: "Silver Metallic", hex: "#C0C0C0" },
  { name: "Umbria Twilight Metallic", hex: "#6F7278" },
  { name: "Ivory Pearl White", hex: "#F5F5F5" },
  { name: "Tan/wheat", hex: "#D2B48C" },
  { name: "Red & Black", hex: "#FF0000" }, // Bicolore
  { name: "Frost White Pearl", hex: "#F5F5F5" },
  { name: "Phantom Black Pearl", hex: "#000000" },
  { name: "Mythos Black Metallic", hex: "#000000" },
  { name: "Brilliant Black Crystal Pearl", hex: "#000000" },
  { name: "Midnight Mocha Metallic", hex: "#654321" },
  { name: "Aspen White Pearl", hex: "#F5F5F5" },
  { name: "Sun Fusion", hex: "#FF8C00" },
  { name: "Dark Charcoal", hex: "#36454F" },
  { name: "Atlas Beige", hex: "#D2B48C" },
  { name: "Palladium Silver Metallic", hex: "#C0C0C0" },
  { name: "Silk Beige", hex: "#F5DEB3" },
  { name: "Selenite Gray Metallic", hex: "#6F7278" },
  { name: "Estoril Blue Metallic", hex: "#1E90FF" },
  { name: "Cosmos Black Metallic", hex: "#000000" },
  { name: "Sahara Beige", hex: "#D2B48C" },
  { name: "White Platinum", hex: "#F5F5F5" },
  { name: "Lunar Gray Metallic", hex: "#6F7278" },
  { name: "Charcoal W/red Stitching", hex: "#36454F" },
  { name: "Bianco Perla (pearl White Tricoat)", hex: "#F5F5F5" },
  { name: "Avorio (ivory)", hex: "#F5F5F5" },
  { name: "Olive Green", hex: "#808000" },
  { name: "Ivory", hex: "#F5F5F5" },
  { name: "Obsidian Black Metallic", hex: "#000000" },
  { name: "Classic Silver Metallic", hex: "#C0C0C0" },
  { name: "Deep Cherry Pearl", hex: "#800000" },
  { name: "Slate Gray", hex: "#708090" },
  { name: "Desert Rock Metallic", hex: "#8B4513" },
  { name: "Blu Passione Mica", hex: "#1E90FF" },
  { name: "Cuoio", hex: "#D2B48C" },
  { name: "Starfire Pearl", hex: "#F5F5F5" },
  { name: "Alien Metallic", hex: "#1E90FF" },
  { name: "Reflex Silver Metallic", hex: "#C0C0C0" },
  { name: "Magnetic Gray Metallic", hex: "#6F7278" },
  { name: "Victory Red", hex: "#D40000" },
  { name: "White Orchid Pearl", hex: "#F5F5F5" },
  { name: "Red Candy Metallic", hex: "#D40000" },
  { name: "White Platinum Metallic", hex: "#F5F5F5" },
  { name: "Black Metallic", hex: "#000000" },
  { name: "Dark Gray Metallic", hex: "#6F7278" },
  { name: "Onyx Black", hex: "#000000" },
  { name: "Lotus Gray Metallic", hex: "#6F7278" },
  { name: "Meteor Gray Mica", hex: "#6F7278" },
  { name: "Bamboo Pearl", hex: "#F5F5F5" },
  { name: "Magnetic Metallic", hex: "#6F7278" },
  { name: "Black Raven", hex: "#000000" },
  { name: "Pyrite Mica", hex: "#D4AF37" },
  { name: "Sand Beige", hex: "#D2B48C" },
  { name: "Wicked White", hex: "#FFFFFF" },
  { name: "Jupiter Red", hex: "#D40000" },
  { name: "Gloss Black", hex: "#000000" },
  { name: "Graphite Luster Metallic", hex: "#383E42" },
  { name: "Black Sapphire Pearl", hex: "#000033" },
  { name: "Light White", hex: "#F5F5F5" },
  { name: "Carbon Black", hex: "#000000" },
  { name: "Metal Bronze Metallic", hex: "#CD7F32" },
  { name: "Steel Black", hex: "#0A0A0A" },
  { name: "Coast Blue Pearl", hex: "#1E90FF" },
  { name: "Taffeta White", hex: "#F5F5F5" },
  { name: "Yulong White", hex: "#FFFFFF" },
  { name: "Ash Black Mica", hex: "#000000" },
  { name: "Frozen White", hex: "#F5F5F5" },
  { name: "Smoky Granite Mica", hex: "#6F7278" },
  { name: "Becketts Black", hex: "#000000" },
  { name: "Bright Silver Metallic", hex: "#C0C0C0" },
  { name: "Graystone", hex: "#6F7278" },
  { name: "Sunset Bronze Mica", hex: "#CD7F32" },
  { name: "Cosmic Blue", hex: "#1E90FF" },
  { name: "Sparkling Black Mica", hex: "#000000" },
  { name: "Starlight Black Mica", hex: "#000000" },
  { name: "Off-black", hex: "#121212" },
  { name: "Summit White", hex: "#FFFFFF" },
  { name: "Black Opal Mica", hex: "#000000" },
  { name: "Aspen Pearl", hex: "#F5F5F5" },
  { name: "Titanium Silver Metallic", hex: "#A8A8A8" },
  { name: "Majestic White Pearl", hex: "#F5F5F5" },
  { name: "Java/dark Brown", hex: "#654321" },
  { name: "Steel Blue Metallic", hex: "#4682B4" },
  { name: "Titan Black/artgray", hex: "#000000" },
  { name: "Moonlight White", hex: "#F5F5F5" },
  { name: "Modern Steel Metallic", hex: "#6F7278" },
  { name: "Blue Onyx Pearl Metallic", hex: "#1E90FF" },
  { name: "Dark Charcoal Pearl", hex: "#36454F" },
  { name: "Tungsten Pearl", hex: "#A8A8A8" },
  { name: "Santorini Black Metallic", hex: "#000000" },
  { name: "Scuba Blue Metallic", hex: "#1E90FF" },
  { name: "Pistachio Beige", hex: "#D2B48C" },
  { name: "Grigio Scuro (dark Gray Metallic)", hex: "#6F7278" },
  { name: "Rescue Green Metallic", hex: "#008000" },
  { name: "Billet Silver Metallic", hex: "#C0C0C0" },
  { name: "Chestnut", hex: "#954535" },
  { name: "Space Black Pearl", hex: "#000000" },
  { name: "Tenorite Gray Metallic", hex: "#6F7278" },
  { name: "Clearwater Blue Metallic", hex: "#1E90FF" },
  { name: "Midnight Black Metallic", hex: "#000000" },
  { name: "Sparkling Bronze Metallic", hex: "#CD7F32" },
  { name: "Venetian Beige", hex: "#D2B48C" },
  { name: "Titanium Metallic", hex: "#A8A8A8" },
  { name: "White Metallic", hex: "#FFFFFF" },
  { name: "Black Pearl", hex: "#000000" },
  { name: "Pearl Red", hex: "#D40000" },
  { name: "Soul Red", hex: "#D40000" },
  { name: "Balck", hex: "#000000" }, // Typo probable pour "Black"
  { name: "Fathom Blue", hex: "#1E90FF" },
  { name: "Pepper White", hex: "#FFFFFF" },
  { name: "Dark Gray/black", hex: "#6F7278" },
];
